title: Raphaëlle Tseng
description: A place to write about what I'm learning and the projects I'm interested in!

email: raphaelletseng@gmail.com
baseurl: ""
url: "raphaelletseng.github.io/articles/"
github_username: raphaelletseng
linkedin_username: raphaëlletseng

markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed

include:
  - assets

future: true
timezone: "Asia/Kuala_Lumpur"


 
